config/routes.rb
AntiVDay::Application.routes.draw do
  resources :penalties

  resources :teams

  resources :spots

  resources :js_events

  resources :media
  
  match '/getAndDeleteEvents' => 'js_events#getAndDelete'
  match '/updateSpot' => 'spots#ajaxUpdate'
  match 'getPenalties' => 'penalties#activeOnly'

  match '/mobile' => 'pages#mobile'
  root :to => 'pages#bracket'

end

app/models/spot.rb
class Spot < ActiveRecord::Base
  belongs_to :team
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  # GET /spots
  # GET /spots.json
  def index
    @spots = Spot.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @spots }
    end
  end

  # GET /spots/1
  # GET /spots/1.json
  def show
    @spot = Spot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @spot }
    end
  end

  # GET /spots/new
  # GET /spots/new.json
  def new
    @spot = Spot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @spot }
    end
  end


  # GET /spots/1/edit
  def edit
    @spot = Spot.find(params[:id])
  end

  # POST /spots
  # POST /spots.json
  def create
    @spot = Spot.new(params[:spot])

    respond_to do |format|
      if @spot.save
        format.html { redirect_to @spot, notice: 'Spot was successfully created.' }
        format.json { render json: @spot, status: :created, location: @spot }
      else
        format.html { render action: "new" }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  def ajaxUpdate
    @spot = Spot.find_by_location(params[:location])

    respond_to do |format|
      if @spot.update_attributes(params[:spot])
        format.html { redirect_to @spot, notice: 'Spot was successfully updated.' }
        format.json { head :ok }
      else
        puts @spot.errors
        format.html { render action: "edit" }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end


  # PUT /spots/1
  # PUT /spots/1.json
  def update
    @spot = Spot.find(params[:id])

    respond_to do |format|
      if @spot.update_attributes(params[:spot])
        format.html { redirect_to @spot, notice: 'Spot was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spots/1
  # DELETE /spots/1.json
  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy

    respond_to do |format|
      format.html { redirect_to spots_url }
      format.json { head :ok }
    end
  end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/_form.html.erb
<%= form_for(@spot) do |f| %>
  <% if @spot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spot.errors.count, "error") %> prohibited this spot from being saved:</h2>

      <ul>
      <% @spot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br />
    <%= f.number_field :location %>
  </div>
  <div class="field">
    <%= f.label :team_id %><br />
    <%= f.text_field :team_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spots/edit.html.erb
<h1>Editing spot</h1>

<%= render 'form' %>

<%= link_to 'Show', @spot %> |
<%= link_to 'Back', spots_path %>

app/views/spots/index.html.erb
<h1>Listing spots</h1>

<table>
  <tr>
    <th>Location</th>
    <th>Team</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @spots.each do |spot| %>
  <tr>
    <td><%= spot.location %></td>
    <td><%= spot.team %></td>
    <td><%= link_to 'Show', spot %></td>
    <td><%= link_to 'Edit', edit_spot_path(spot) %></td>
    <td><%= link_to 'Destroy', spot, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Spot', new_spot_path %>

app/views/spots/new.html.erb
<h1>New spot</h1>

<%= render 'form' %>

<%= link_to 'Back', spots_path %>

app/views/spots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Location:</b>
  <%= @spot.location %>
</p>

<p>
  <b>Team:</b>
  <%= @spot.team %>
</p>


<%= link_to 'Edit', edit_spot_path(@spot) %> |
<%= link_to 'Back', spots_path %>