config/routes.rb
AntiVDay::Application.routes.draw do
  resources :penalties

  resources :teams

  resources :spots

  resources :js_events

  resources :media
  
  match '/getAndDeleteEvents' => 'js_events#getAndDelete'
  match '/updateSpot' => 'spots#ajaxUpdate'
  match 'getPenalties' => 'penalties#activeOnly'

  match '/mobile' => 'pages#mobile'
  root :to => 'pages#bracket'

end

app/models/js_event.rb
class JsEvent < ActiveRecord::Base
end

app/controllers/js_events_controller.rb
class JsEventsController < ApplicationController
  # GET /js_events
  # GET /js_events.json
  def getAndDelete
    @js_events = JsEvent.order('created_at ASC').all

    @js_events.each do |e|
      e.destroy()
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @js_events }
    end
  end
  
  def index
    @js_events = JsEvent.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @js_events }
    end
  end

  # GET /js_events/1
  # GET /js_events/1.json
  def show
    @js_event = JsEvent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @js_event }
    end
  end

  # GET /js_events/new
  # GET /js_events/new.json
  def new
    @js_event = JsEvent.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @js_event }
    end
  end

  # GET /js_events/1/edit
  def edit
    @js_event = JsEvent.find(params[:id])
  end

  # POST /js_events
  # POST /js_events.json
  def create
    @js_event = JsEvent.new(params[:js_event])

    respond_to do |format|
      if @js_event.save
        format.html { redirect_to @js_event, notice: 'Js event was successfully created.' }
        format.json { render json: @js_event, status: :created, location: @js_event }
      else
        format.html { render action: "new" }
        format.json { render json: @js_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /js_events/1
  # PUT /js_events/1.json
  def update
    @js_event = JsEvent.find(params[:id])

    respond_to do |format|
      if @js_event.update_attributes(params[:js_event])
        format.html { redirect_to @js_event, notice: 'Js event was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @js_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /js_events/1
  # DELETE /js_events/1.json
  def destroy
    @js_event = JsEvent.find(params[:id])
    @js_event.destroy

    respond_to do |format|
      format.html { redirect_to js_events_url }
      format.json { head :ok }
    end
  end
end

app/helpers/js_events_helper.rb
module JsEventsHelper
end

app/views/js_events/_form.html.erb
<%= form_for(@js_event) do |f| %>
  <% if @js_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@js_event.errors.count, "error") %> prohibited this js_event from being saved:</h2>

      <ul>
      <% @js_event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :functionName %><br />
    <%= f.text_field :functionName %>
  </div>
  <div class="field">
    <%= f.label :args %><br />
    <%= f.text_field :args %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/js_events/edit.html.erb
<h1>Editing js_event</h1>

<%= render 'form' %>

<%= link_to 'Show', @js_event %> |
<%= link_to 'Back', js_events_path %>

app/views/js_events/getAndDelete.html.erb
<h1>Listing js_events</h1>

<table>
  <tr>
    <th>Functionname</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @js_events.each do |js_event| %>
  <tr>
    <td><%= js_event.functionName %></td>
    <td><%= link_to 'Show', js_event %></td>
  </tr>
<% end %>
</table>

<br />

app/views/js_events/index.html.erb
<h1>Listing js_events</h1>

<table>
  <tr>
    <th>Functionname</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @js_events.each do |js_event| %>
  <tr>
    <td><%= js_event.functionName %></td>
    <td><%= link_to 'Show', js_event %></td>
    <td><%= link_to 'Edit', edit_js_event_path(js_event) %></td>
    <td><%= link_to 'Destroy', js_event, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Js event', new_js_event_path %>

app/views/js_events/new.html.erb
<h1>New js_event</h1>

<%= render 'form' %>

<%= link_to 'Back', js_events_path %>

app/views/js_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Functionname:</b>
  <%= @js_event.functionName %>
</p>


<%= link_to 'Edit', edit_js_event_path(@js_event) %> |
<%= link_to 'Back', js_events_path %>