config/routes.rb
AntiVDay::Application.routes.draw do
  resources :penalties

  resources :teams

  resources :spots

  resources :js_events

  resources :media
  
  match '/getAndDeleteEvents' => 'js_events#getAndDelete'
  match '/updateSpot' => 'spots#ajaxUpdate'
  match 'getPenalties' => 'penalties#activeOnly'

  match '/mobile' => 'pages#mobile'
  root :to => 'pages#bracket'

end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  # GET /media
  # GET /media.json
  def index
    @media = Medium.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @media.shuffle() }
    end
  end

  # GET /media/1
  # GET /media/1.json
  def show
    @medium = Medium.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @medium }
    end
  end

  # GET /media/new
  # GET /media/new.json
  def new
    @medium = Medium.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @medium }
    end
  end

  # GET /media/1/edit
  def edit
    @medium = Medium.find(params[:id])
  end

  # POST /media
  # POST /media.json
  def create
    @medium = Medium.new(params[:medium])

    respond_to do |format|
      if @medium.save
        format.html { redirect_to @medium, notice: 'Medium was successfully created.' }
        format.json { render json: @medium, status: :created, location: @medium }
      else
        format.html { render action: "new" }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /media/1
  # PUT /media/1.json
  def update
    @medium = Medium.find(params[:id])

    respond_to do |format|
      if @medium.update_attributes(params[:medium])
        format.html { redirect_to @medium, notice: 'Medium was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media/1
  # DELETE /media/1.json
  def destroy
    @medium = Medium.find(params[:id])
    @medium.destroy

    respond_to do |format|
      format.html { redirect_to media_url }
      format.json { head :ok }
    end
  end
end

app/helpers/media_helper.rb
module MediaHelper
end

app/views/media/_form.html.erb
<%= form_for(@medium) do |f| %>
  <% if @medium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medium.errors.count, "error") %> prohibited this medium from being saved:</h2>

      <ul>
      <% @medium.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :format %><br />
    <%= f.text_field :format %>
  </div>
  <div class="field">
    <%= f.label :src %><br />
    <%= f.text_field :src %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :artist %><br />
    <%= f.text_field :artist %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/media/edit.html.erb
<h1>Editing medium</h1>

<%= render 'form' %>

<%= link_to 'Show', @medium %> |
<%= link_to 'Back', media_path %>

app/views/media/index.html.erb
<h1>Listing media</h1>

<table>
  <tr>
    <th>Format</th>
    <th>Src</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @media.each do |medium| %>
  <tr>
    <td><%= medium.format %></td>
    <td><%= medium.src %></td>
    <td><%= link_to 'Show', medium %></td>
    <td><%= link_to 'Edit', edit_medium_path(medium) %></td>
    <td><%= link_to 'Destroy', medium, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Medium', new_medium_path %>

app/views/media/new.html.erb
<h1>New medium</h1>

<%= render 'form' %>

<%= link_to 'Back', media_path %>

app/views/media/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Format:</b>
  <%= @medium.format %>
</p>

<p>
  <b>Src:</b>
  <%= @medium.src %>
</p>

<% if @medium.format == "audio" %>
  <div class="album">
    <img src="/assets/media/<%= @medium.src.gsub("mp3","jpg") %>" />
  </div>
  <audio controls src="/assets/media/<%= @medium.src %>"></audio>
<% else %>
  <div class="video">
    <video id="myVideo" controls src="/assets/media/<%= @medium.src %>" style="-webkit-box-reflect: below 0px -webkit-gradient(linear, left top, left bottom, from(transparent), to(black),color-stop(0.4, transparent));"></video> 
<% end %>

<%= link_to 'Edit', edit_medium_path(@medium) %> |
<%= link_to 'Back', media_path %>
<style>
    video {
    -webkit-transition-property: -webkit-transform;
    -webkit-transition-duration: 4s;
    }
 
    body { -webkit-perspective: 500;}
</style>
<script type="text/javascript">
var flipped = 0 ;
 
function flipper() {
    if (flipped)
        myVideo.style.webkitTransform = "rotateY(0deg)";
    else
        myVideo.style.webkitTransform = "rotateY(180deg)";
    flipped = !flipped ;
}
 
</script>