config/routes.rb
AntiVDay::Application.routes.draw do
  resources :penalties

  resources :teams

  resources :spots

  resources :js_events

  resources :media
  
  match '/getAndDeleteEvents' => 'js_events#getAndDelete'
  match '/updateSpot' => 'spots#ajaxUpdate'
  match 'getPenalties' => 'penalties#activeOnly'

  match '/mobile' => 'pages#mobile'
  root :to => 'pages#bracket'

end

app/models/penalty.rb
class Penalty < ActiveRecord::Base
end

app/controllers/penalties_controller.rb
class PenaltiesController < ApplicationController
  def activeOnly
    @penalties = Penalty.find(:all, :conditions => ["active == ?", true])

    respond_to do |format|
      format.json { render json: @penalties }
    end
  end
  # GET /penalties
  # GET /penalties.json
  def index
    @penalties = Penalty.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @penalties }
    end
  end

  # GET /penalties/1
  # GET /penalties/1.json
  def show
    @penalty = Penalty.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @penalty }
    end
  end

  # GET /penalties/new
  # GET /penalties/new.json
  def new
    @penalty = Penalty.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @penalty }
    end
  end

  # GET /penalties/1/edit
  def edit
    @penalty = Penalty.find(params[:id])
  end

  # POST /penalties
  # POST /penalties.json
  def create
    @penalty = Penalty.new(params[:penalty])

    respond_to do |format|
      if @penalty.save
        format.html { redirect_to @penalty, notice: 'Penalty was successfully created.' }
        format.json { render json: @penalty, status: :created, location: @penalty }
      else
        format.html { render action: "new" }
        format.json { render json: @penalty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /penalties/1
  # PUT /penalties/1.json
  def update
    @penalty = Penalty.find(params[:id])

    respond_to do |format|
      if @penalty.update_attributes(params[:penalty])
        format.html { redirect_to @penalty, notice: 'Penalty was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @penalty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /penalties/1
  # DELETE /penalties/1.json
  def destroy
    @penalty = Penalty.find(params[:id])
    @penalty.destroy

    respond_to do |format|
      format.html { redirect_to penalties_url }
      format.json { head :ok }
    end
  end
end

app/helpers/penalties_helper.rb
module PenaltiesHelper
end

app/views/penalties/_form.html.erb
<%= form_for(@penalty) do |f| %>
  <% if @penalty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@penalty.errors.count, "error") %> prohibited this penalty from being saved:</h2>

      <ul>
      <% @penalty.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :alcohol %><br />
    <%= f.check_box :alcohol %>
  </div>
  <div class="field">
    <%= f.label :crossfit %><br />
    <%= f.check_box :crossfit %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :abrev %><br />
    <%= f.text_field :abrev %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/penalties/edit.html.erb
<h1>Editing penalty</h1>

<%= render 'form' %>

<%= link_to 'Show', @penalty %> |
<%= link_to 'Back', penalties_path %>

app/views/penalties/index.html.erb
<h1>Listing penalties</h1>

<table>
  <tr>
    <th>Alcohol</th>
    <th>Crossfit</th>
    <th>Active</th>
    <th>Name</th>
    <th>Abrev</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @penalties.each do |penalty| %>
  <tr>
    <td><%= penalty.alcohol %></td>
    <td><%= penalty.crossfit %></td>
    <td><%= penalty.active %></td>
    <td><%= penalty.name %></td>
    <td><%= penalty.abrev %></td>
    <td><%= link_to 'Show', penalty %></td>
    <td><%= link_to 'Edit', edit_penalty_path(penalty) %></td>
    <td><%= link_to 'Destroy', penalty, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Penalty', new_penalty_path %>

app/views/penalties/new.html.erb
<h1>New penalty</h1>

<%= render 'form' %>

<%= link_to 'Back', penalties_path %>

app/views/penalties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Alcohol:</b>
  <%= @penalty.alcohol %>
</p>

<p>
  <b>Crossfit:</b>
  <%= @penalty.crossfit %>
</p>

<p>
  <b>Active:</b>
  <%= @penalty.active %>
</p>

<p>
  <b>Name:</b>
  <%= @penalty.name %>
</p>

<p>
  <b>abrev:</b>
  <%= @penalty.abrev %>
</p>


<%= link_to 'Edit', edit_penalty_path(@penalty) %> |
<%= link_to 'Back', penalties_path %>